# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

before_script:
 - composer self-update
 - composer update

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "lezhnev.work@gmail.com"